### Crear un nuevo Rol
POST http://localhost:10000/api/roles
Content-Type: application/json
Authorization: Bearer

{
  "nombre": ""
}
###

### Obtener todos los roles individual o grupalmente.
GET http://localhost:10000/api/roles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZiYjM4MmRiYzE1NmYzYWJlZDNmYSIsImVtYWlsIjoic2ViYXNAZ21haWwuY29tIiwibm9tYnJlcyI6IlNlYmFzIiwiYXBlbGxpZG9zIjoiQXJib2wiLCJyb2wiOiI2NzVkZDQxNTA5MWU0YzYyM2YyNWMwMTUiLCJpYXQiOjE3MzQ1NTY2NDUsImV4cCI6MTczNDU5OTg0NX0.AhKfSd_HA0d8od11HaRlnNXvL3VhuJ8fd5g2poJeSTU
###

### Actualizar un rol por su nombre
PUT http://localhost:10000/api/roles/
Content-Type: application/json

{
  "nombre": ""
}
###

### Eliminar un rol por su ID
DELETE http://localhost:10000/api/roles/lllla
###



