### Crear un nuevo Rol
POST http://localhost:10000/api/roles
Content-Type: application/json

{
  "nombre": "asistente"
}

###

### Obtener todos los roles
GET http://localhost:10000/api/roles

###

### Obtener un rol por su ID
GET http://localhost:10000/api/roles/6753df4ecbad7dc405cf529c

###


### Actualizar un rol por su ID
PUT http://localhost:10000/api/roles/6753ef87358975532e46d103
Content-Type: application/json

{
  "nombre": "cliente modificado"
}


### Eliminar un rol por su ID
DELETE http://localhost:10000/api/roles/6753dfbf3b785f2441eb041d
