### Crear un nuevo Rol
POST http://localhost:10000/api/roles
Content-Type: application/json

{
  "nombre": "cosit"
}
###

### Obtener todos los roles
GET http://localhost:10000/api/roles
###

### Obtener un rol por su nombre
GET http://localhost:10000/api/roles/asistente
###


### Actualizar un rol por su nombre
PUT http://localhost:10000/api/roles/asistent
Content-Type: application/json

{
  "nombre": "asistente"
}
###

### Eliminar un rol por su ID
DELETE http://localhost:10000/api/roles/675cc151d1ce994b119f9d9d
###



