### Crear un nuevo usuario.
POST http://localhost:10000/api/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjNhZTI3NTczOTVjOTllNTYxMTJhYSIsInJvbCI6ImFzaXN0ZW50ZSIsImlhdCI6MTczNDY3MTU2MCwiZXhwIjoxNzM0NzE0NzYwfQ.4MB0itc7xBJWraeAeKy2K9QXqqtbRlNN6uig7HV-F90

{
  "numeroIdentificacion": "148368796516549",
  "nombres": "Luz",
  "apellidos": "Villegas",
  "telefono": "6589789223321132",
  "email": "luz@gmail.com",
  "password": "luzbel123456",
  "nombre_rol": "administrador"
}
###

### Lista de usuarios individual y o grupalmente.
GET http://localhost:10000/api/usuarios/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZiYjM4MmRiYzE1NmYzYWJlZDNmYSIsInJvbCI6ImFzaXN0ZW50ZSIsImlhdCI6MTczNTk2Nzk5NCwiZXhwIjoxNzM1OTc1MTk0fQ.KaWNDm5JgCng7UH2HTJHlAgZs7qdiry6ED9buYO2IA4
###

### Editar un usuario por su numero de identificacion.
PUT http://localhost:10000/api/usuarios/2289897
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZiYjM4MmRiYzE1NmYzYWJlZDNmYSIsInJvbCI6ImFzaXN0ZW50ZSIsImlhdCI6MTczNTI1NjczNSwiZXhwIjoxNzM1MjYzOTM1fQ.3-lwakImx1hQcBwBFjFahBiSMSvrsa3ZnXP3AyDHdns


{
  "nuevoNumeroIdentificacion": "2289897",
  "nombres": "Leonardo",
  "apellidos": "Rivas",
  "telefono": "3027887963",
  "email": "leonardodrv1204@gmail.com",
  "password": "leonardo123456",
  "nombre_rol": "asistente"
}
###

### Eliminar un usuario por su numero de Identificacion.
DELETE http://localhost:10000/api/usuarios/958613894651302
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZiYjM4MmRiYzE1NmYzYWJlZDNmYSIsInJvbCI6ImFzaXN0ZW50ZSIsImlhdCI6MTczNTI1NjczNSwiZXhwIjoxNzM1MjYzOTM1fQ.3-lwakImx1hQcBwBFjFahBiSMSvrsa3ZnXP3AyDHdns
###