### Crear un nuevo usuario.
POST http://localhost:10000/api/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZiYjM4MmRiYzE1NmYzYWJlZDNmYSIsImVtYWlsIjoic2ViYXNAZ21haWwuY29tIiwibm9tYnJlcyI6IlNlYmFzIiwiYXBlbGxpZG9zIjoiQXJib2wiLCJyb2wiOiI2NzVkZDQxNTA5MWU0YzYyM2YyNWMwMTUiLCJpYXQiOjE3MzQ1ODU3OTIsImV4cCI6MTczNDYyODk5Mn0.L_Nljpl9pTCNoCvVsBqU2MQWUUqcifDzLYR5oFOiGeo 

{
  "numeroIdentificacion": "5665448979651651",
  "nombres": "Diego Alejandro",
  "apellidos": "Farias Villegas",
  "telefono": "651564510",
  "email": "diego@gmail.com",
  "password": "diego123456789",
  "nombre_rol": "asistente"
}
###

### Lista de usuarios individual y o grupalmente.
GET http://localhost:10000/api/usuarios/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZiYjM4MmRiYzE1NmYzYWJlZDNmYSIsImVtYWlsIjoic2ViYXNAZ21haWwuY29tIiwibm9tYnJlcyI6IlNlYmFzIiwiYXBlbGxpZG9zIjoiQXJib2wiLCJyb2wiOiI2NzVkZDQxNTA5MWU0YzYyM2YyNWMwMTUiLCJpYXQiOjE3MzQ1ODU3OTIsImV4cCI6MTczNDYyODk5Mn0.L_Nljpl9pTCNoCvVsBqU2MQWUUqcifDzLYR5oFOiGeo
###

### Editar un usuario por su numero de identificacion.
PUT http://localhost:10000/api/usuarios/547878454651516651651
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZiYjM4MmRiYzE1NmYzYWJlZDNmYSIsImVtYWlsIjoic2ViYXNAZ21haWwuY29tIiwibm9tYnJlcyI6IlNlYmFzIiwiYXBlbGxpZG9zIjoiQXJib2wiLCJyb2wiOiI2NzVkZDQxNTA5MWU0YzYyM2YyNWMwMTUiLCJpYXQiOjE3MzQ1ODU3OTIsImV4cCI6MTczNDYyODk5Mn0.L_Nljpl9pTCNoCvVsBqU2MQWUUqcifDzLYR5oFOiGeo


{
  "nuevoNumeroIdentificacion": "547878454651516651651",
  "nombres": "Samuel Abraham",
  "apellidos": "Rivas Villegas",
  "telefono": "025166515169478489",
  "email": "samuel@gmail.com",
  "password": "samuelrivas123456789",
  "nombre_rol": "administrador"
}
###

### Eliminar un usuario por su numero de Identificacion.
DELETE http://localhost:10000/api/usuarios/147
###